"""empty message

Revision ID: f89503c97ec6
Revises: 
Create Date: 2024-04-01 05:34:32.618235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89503c97ec6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.alter_column('carriers', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Создатель заказа')
    op.alter_column('suppliers_orders', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Создатель заказа')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers_orders', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Создатель заказа')
    op.alter_column('carriers', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Создатель заказа')
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
